language: python
python:
- '3.7'
script:
- nose2 -v
deploy:
  provider: pypi
  username: refaelkohen
  password:
    secure: HXYD54gXx+MNXa1m7mKKlLkdFLH3QkaHRaDySC3ipzwTi1V84eGrLOKNftbJdAa6nBiyfdxyTUJd9ihuHPpVPXM4+jNf4asgHjfEZFQig6YiWTS92/j2IUoTf4gn+/nP9qVN9nHm0Yx9ZxnK62p3Mf0kLdpEXnZ0LbPXx8IKsHztuYr1uIXZ4pNxpUxgP/5kTgJKRpt+RVcDni2Q/q4fqorqRIozCPGpCjQVZioOOdiQJZIEvKDMx+It7wMNwG+APBbRWsTXA8+gaYYKH0zDDd2dlu8z2vqW2oCG+q+dt8me/CT12MbeRGWCDY1TzKZ3SYRGlSq/gAnLfBZG/XY7XQsolEWh55BtkUqrmZvtj3GXkyXBPKvcVkoGOv+0q7v/6e/+fOQMq8Q6AD9ZLyGMvuNgLL9Gk1Vz3ycAGPvc4UUOHd40TL5wSyFkolzldL1EJSNnp1MsZy+Bvx3XF8DM/G39Hklqpty6HIgB+yy+aop1dMCpyiFWzaP6sgf4Sozf8ciPa5O2YK+Hz2rnvB7kHK9vVJyqjBHAJ1HSlh593KIRVosf+v2wTICZmAICVx4WI0+6bSJAeSPn+jJawK2SYyL0r41/4y3ZuCTWSE8IOu4UrRc67EBhfXNweY8jQB9siVAyZyvXxD3z49eG9unf2TXSCQTJF3HwOnEug71TeRU=
  server: https://test.pypi.org/legacy/
