language: python
python:
- '3.7'
script:
- nose2 -v
deploy:
  provider: pypi
  username: refael.kohen
  password:
    secure: r28WNmE+l+pn0BZ/+cY2MlRuENTIV70pQU3XVMxUdBA0qkSiuPdSaoXwycVqGxOB3fa/QCSjgmyu5kTeQ+yqEFHEPVLuMNFdzROM+adwbNUxOVHFunUX6HWbmSpevJ2pJQlnxc61MFOD8EguezUHv1dl+Ro8ZlksRWAliUFTiTgvHgZDEYeH7AkScLKXrwGY7EFZ0bp2UOmSYjZPMy+w/zjAJjpSRUAgmfJ+ue7hngI9Vsd9SsZ8pUotADyRAXl3E8CU12+tx2aheDPchA3JNRuUc4ktKXcUIxwUT1TvEJGVG0ztw3RYi/cOUw3OsQvInnUp9ldLERfYcu2SFw3qdUXeRlLHZHg0ODnQQQXZc19CPWYZj84uMKAJBIj88ZWcS1F0i0uPfv1R0b7EHYEtGYSvws+cKrxoDTXnM9Q35JAxkKO7NTJRzAP1Qn/2lv2ih/qpF31NdMvdKkEbZVG6flIL1KdaUu4PzyT282nenvoUVD807nxbnv73J4jq75Mf49ctI44yHOgIwdH73yvkST2sXtHMulSWc8e5sQBe7DcdNmgor0yUMdO/9uPp3gOxjoa2+PtvattxBA/GcxtRvUGw8Ks8Ta7+ea+3l8adHNLeU80XjLdSNg/l0IlJHMwhf8gCTlsku73E05R3irOvGf+urplEWZG4qaIYF0dnPG4=
