language: python
python:
- '3.7'
script:
- nose2 -v
deploy:
  provider: pypi
  username: "refaelkohen"
  password:
    secure: "AJdibPolJRrcvX+ZKSGVdpD+tW0iJK8P7ipR/gI6IDuigwArOf/WM5bybyW/jhaoiHnI3YmjJZmpwV4K6wLxO3ZkDg7s0JIhkqILafS4A5OgVD8ocuyUb3TgJAnCJMGnJ7OC5IddB4er3HCvUdazqh15vEu2Lp5zJJW49U1aQ7nUU2SvF93s57ShoimAfI4YUVz31oYCbi/YV9lgIumAUHEqdLxcEW0BQbyiIwMDajT/5vlNB6bARYxdkAKbbMQivOB719kmXKwB+7kpUu4NGJlhjyrZnufnU5/rckHK64QC0ArrurXbM3EN4qK1mYehU+T59mmBb2Eid2Wn4tkKGI/VIQ9uMUHMoCm8wxHNMRpr1RBslU9IbGz3xGv2eM+IMrhL4Zy/FAYzyOKkb0hHvuWj5SbnAlqwGn1Nh0JnC3RMwIz68zX4mWX5vvuZESupXnfu2Sy2wOWZgmmnJqiwBVnbsLbWJRcQEg3tKRGWIDybCKpQFBaEfIrLo9giH6yoDHBD3Ymdr7BppG8gY8jqQA+8YZJ9vcFUboBvsK5lOERUp8YaEbC3R93SIEKL0fBBUI/B9bzicrb0RA8KjFGPUDGuufAzhhtg031zArK5OSjQ6Aus93uKRxZmfHUnUkyFO5WedHs0zyzLfeUl1XtadhJSZdeB49owIiePXiP4QUQ="
  server: https://test.pypi.org/legacy/
