language: python
python:
- '3.7'
script:
- nose2 -v
deploy:
  provider: pypi
  username: refaelkohen
  password:
    secure: M3PJCCRIPYsMy+4Zb2fn0KpT1YtmWuL62ev+Yav4YaAqduVzdD58NS6smgrPDenw5ZIJauRbPUn+7bVt5kxvWbZh7oMA3LLsCY4DmHahjk11qV04Ciw8fV/y4ybh4DRWsJUg0wZMUWU48fFxRb2FcIkPfTaaygMTfKrb/UhA    DQcXG/fSaJMadpgb0dw7MucI0QtJhzNrdJZ4KAaUNjojjZCLVMGC2OEQiZEKyEGv/M/ZmiVGLCPFKBuapoP7JdWEumG0JlwSu5qFU+Az/984bBu6ZF5+ilEsnAiADwH3ABUo7IVVesSydeu+ElxNMHuydwk7iU+24+pUeA4msBoQ276D    kkDQRLflwvQCaUUSrFBWWxLtUmoSF/Lm215IwaW9Zx8ziQQvJ0Gq0bvu29GYDA1sSwlnwODYZWh0Cz7cm7PtkE72rwKQoE2mRYgube7HpOrwq91ilk2FFuE6FDhFXe/LDJBtHqaxa6W0CcoW8N0Qg47e6GPf1Fwq2bd9jb5PWNOGn/OR    AIAOV6QeFrmD1rVMrl8WflD00N1L8EP37aPiD7QZ3/w+/ByHH60E/Wa9Sf7qfzr0hsmBloTTBWF6UtJ0H0ZBLGjxfFqB6r9a3QkAd9r+VVloks8c45fOi1zoYRVRexMxxLx2hLVJbLAu+xZCxosxqlD7o5pema6DbCY=
  server: https://test.pypi.org/simple/
